services:
  backend:
    build: 
      context : .
      dockerfile : backend.dockerfile
    ports:
      - "5000:5000"

  frontend:
    build: 
      context : . 
      dockerfile : frontend.dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend


